name: HotFix
version: ${project.version}
#website:
author: RoboMWM
main: me.robomwm.HotFix.Main
softdepend: [AbsorptionShields]
api-version: '1.14'
commands:
    hotfix:
      description: no
      usage: /hotfix <target> <name>
      permission: hotfix.no
      permission-message: Ayyy leMayo
    goldleggings:
      usage: /goldleggings <levitation amplifier> <jump amplifier>
   
permissions:
    hotfix.no:
        description: Permission to /hotfix
        default: op