name: HotFix
version: ${project.version}
#website:
author: RoboMWM
main: me.robomwm.HotFix.Main
commands:
   hotfix:
      description: no
      usage: /hotfix <target> <name>
      permission: hotfix.no
      permission-message: Ayyy leMayo
permissions:
    hotfix.no:
        description: Permission to /hotfix
        default: op