name: HotFix
version: ${project.version}
#website:
author: RoboMWM
main: me.robomwm.HotFix.Main
softdepend: [AbsorptionShields]
api-version: '1.14'
commands:
    hotfix:
      description: no
      usage: /hotfix <target> <name>
      permission: hotfix.no
      permission-message: Ayyy leMayo
    waxsigns:
      description: Wax all signs in specified world or current world
      usage: /waxsigns [world]
      permission: hotfix.waxsigns
      permission-message: Ayyy leMayo
    goldleggings:
      usage: /goldleggings <levitation amplifier> <jump amplifier>
    
permissions:
    hotfix.no:
        description: Permission to /hotfix
        default: op
    hotfix.waxsigns:
        description: Permission to wax all signs
        default: op